// EEG feature gallery (/admin/eeg-lab/gallery): what the synthetic renderer draws, one page per feature, for editors.
//
// The item list is src/data/eeg-gallery.json, generated by scripts/eeg-gallery-publish.mts from the catalog in
// research/eeg-atlas/gallery-<date>/ (specs rendered with the committed renderer). Images are in the private storage
// bucket GALLERY_BUCKET and reach the browser only as signed URLs from /api/admin/eeg-gallery (editor role).
// Review state and notes are in public.eeg_gallery_state / eeg_gallery_notes.

export const GALLERY_BUCKET = "eeg-gallery";
export const GALLERY_SIGNED_URL_TTL_S = 3 * 3600;

export type GalleryStatus = "new" | "needs_review" | "accepted";
export const STATUS_LABEL: Record<GalleryStatus, string> = {
  new: "New", needs_review: "Needs review", accepted: "Accepted",
};

export type GalleryCategory =
  | "normal" | "sleep" | "variants" | "artifacts" | "slowing" | "interictal" | "seizures" | "generalized"
  | "acns" | "neonatal" | "sedation" | "trends";

/** Teaching order, grouped for the rail. */
export const CATEGORY_GROUPS: { label: string; categories: { id: GalleryCategory; label: string }[] }[] = [
  {
    label: "Background",
    categories: [
      { id: "normal", label: "Normal backgrounds" },
      { id: "sleep", label: "Sleep" },
      { id: "variants", label: "Normal variants" },
      { id: "artifacts", label: "Artifacts" },
    ],
  },
  {
    label: "Pathology",
    categories: [
      { id: "slowing", label: "Abnormal non-epileptiform" },
      { id: "interictal", label: "Interictal epileptiform" },
      { id: "seizures", label: "Focal seizures" },
      { id: "generalized", label: "Generalized epilepsies" },
      { id: "acns", label: "ACNS critical care" },
    ],
  },
  {
    label: "Special populations and trends",
    categories: [
      { id: "neonatal", label: "Neonatal" },
      { id: "sedation", label: "Sedation" },
      { id: "trends", label: "Trends (qEEG)" },
    ],
  },
];

export const CATEGORY_ORDER: GalleryCategory[] = CATEGORY_GROUPS.flatMap((g) => g.categories.map((c) => c.id));
export const CATEGORY_LABEL = Object.fromEntries(
  CATEGORY_GROUPS.flatMap((g) => g.categories.map((c) => [c.id, c.label])),
) as Record<GalleryCategory, string>;

export type GalleryTags = {
  age?: string;
  state?: string;
  montage?: string;
  sensitivity_uv_mm?: number;
  acns?: string;
};

export type GalleryItem = {
  id: string;
  title: string;
  category: GalleryCategory;
  subcategory: string;
  caption: string;
  tags: GalleryTags;
  kind: string;             // eeg_page | qeeg_panel | aeeg | composite
  rendererVersion: string;
  specHash: string;
  width: number;
  height: number;
  path: string;             // object path in GALLERY_BUCKET (PNG)
  thumbPath: string;        // 800-px WebP
};

export type GalleryManifest = { rendererVersion: string; generated: string; items: GalleryItem[] };

export type GalleryState = {
  status: GalleryStatus;
  rendererVersion: string;
  updatedByName: string | null;
  updatedAt: string;
};

export type GalleryNote = {
  id: string;
  itemId: string;
  rendererVersion: string;
  authorName: string | null;
  body: string;
  createdAt: string;
};

/** The status an editor sees: a status set against an older render reads as New, so every re-render gets looked at. */
export function effectiveStatus(item: GalleryItem, st: GalleryState | undefined): GalleryStatus {
  if (!st || st.rendererVersion !== item.rendererVersion) return "new";
  return st.status;
}

const MONTAGE_SHORT: Record<string, string> = {
  longitudinal_bipolar: "Longitudinal bipolar", transverse_bipolar: "Transverse bipolar",
  referential: "Referential", average: "Average reference", laplacian: "Laplacian",
  double_distance: "Double distance", neonatal: "Neonatal", circumferential: "Circumferential",
};

export function montageLabel(m?: string): string | null {
  if (!m) return null;
  return MONTAGE_SHORT[m] ?? m.replace(/_/g, " ");
}

export function isTrend(item: GalleryItem): boolean {
  return item.kind === "qeeg_panel" || item.kind === "aeeg";
}

/** Chips in display order: age, state, montage, sensitivity. */
export function paramChips(item: GalleryItem): string[] {
  const t = item.tags;
  const out: string[] = [];
  if (t.age) out.push(t.age.replace(/_/g, " "));
  if (t.state && t.state !== "unknown") out.push(t.state);
  if (isTrend(item)) out.push(item.kind === "aeeg" ? "aEEG trend" : "Trend panel");
  else {
    const m = montageLabel(t.montage);
    if (m) out.push(m);
  }
  if (t.sensitivity_uv_mm && !isTrend(item)) out.push(`${t.sensitivity_uv_mm} µV/mm`);
  return out;
}

/** Alt text composed from the data (UX spec §8). */
export function altText(item: GalleryItem): string {
  const parts = [item.title + ".", "Synthetic EEG"];
  const chips = paramChips(item);
  if (chips.length) parts.push(chips.join(", ") + ".");
  return `${parts.join(" ")} ${item.caption}`;
}

/** Lower-case haystack for search: title, caption, subcategory, ACNS tag, category label. */
export function searchText(item: GalleryItem): string {
  return [item.title, item.caption, item.subcategory, item.tags.acns ?? "", CATEGORY_LABEL[item.category] ?? ""]
    .join(" ").toLowerCase();
}
